spring.application.name=springbootpractice

# Actuator properties
# `management.endpoints.web.exposure.include` can be set to '*'
management.endpoints.web.exposure.include=health,info
management.info.env.enabled=true

info.app.name=My Spring Boot Practice
info.app.description=A cool practice for me!
info.app.version=1.0.0